[package]
name = "solana_prediction"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Your Team <dev@example.com>"]

[lib]
name = "solana_prediction"
crate-type = ["cdylib", "lib"]

[dependencies]
anchor-lang = "0.29.0"
solana-program = "1.18.26"

[features]
idk-build = []
no-entrypoint = []
