[toolchain]
anchor_version = "0.32.1"

[features]
seeds = true
skip-lint = false

[programs.localnet]
solana_prediction = "8ADZwnjeRCQ9Zkeafqb7XhmtEWC1XtVEajATzrtTr1nu"

[programs.devnet]
solana_prediction = "8ADZwnjeRCQ9Zkeafqb7XhmtEWC1XtVEajATzrtTr1nu"

[programs.mainnet]
solana_prediction = "8ADZwnjeRCQ9Zkeafqb7XhmtEWC1XtVEajATzrtTr1nu"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
build = "anchor build"
deploy = "anchor deploy"
